/* textchum.h — C interface to the Textchum core. Generated by cbindgen; do not edit. */

#pragma once

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event kind: reply to `tc_app_ping`.
 */
#define TC_EVENT_PONG 1

/**
 * Event kind: a language server published diagnostics. `path` is the
 * file; `payload` is a JSON array of `{line, character, endLine,
 * endCharacter, severity, message}` (LSP positions: zero-based line,
 * UTF-16 column).
 */
#define TC_EVENT_DIAGNOSTICS 2

/**
 * Event kind: a language-server instance changed state. `server` is the
 * server id, `path` its project root, `status` one of
 * starting/running/not-found/failed/exited, `payload` a human-readable
 * message.
 */
#define TC_EVENT_SERVER_STATUS 3

/**
 * Event kind: a language server answered a request. `seq` is the id the
 * request call returned; `payload` is the response's `result` as JSON.
 */
#define TC_EVENT_LSP_RESPONSE 4

/**
 * Appearance choice: follow the system.
 */
#define TC_APPEARANCE_SYSTEM 0

/**
 * Appearance choice: always light.
 */
#define TC_APPEARANCE_LIGHT 1

/**
 * Appearance choice: always dark.
 */
#define TC_APPEARANCE_DARK 2

/**
 * Style flag: render bold.
 */
#define TC_STYLE_BOLD 1

/**
 * Style flag: render italic.
 */
#define TC_STYLE_ITALIC 2

/**
 * Root handle for a core instance. Create with [`tc_app_new`], release with
 * [`tc_app_free`]. Owns the language-server pool.
 *
 * Field order is load-bearing: the pool holds an event-sender clone, and
 * `App`'s drop joins its dispatcher thread, which only ends once every
 * sender is gone — so the pool must drop first.
 */
typedef struct TcApp TcApp;

/**
 * An in-memory text document. Create with [`tc_buffer_new`], release with
 * [`tc_buffer_free`].
 */
typedef struct TcBuffer TcBuffer;

/**
 * The application's JSON-backed configuration. Create with
 * [`tc_config_load`], release with [`tc_config_free`].
 */
typedef struct TcConfig TcConfig;

/**
 * A text document: buffer, undo history, path and encoding. Create with
 * [`tc_document_new`] or [`tc_document_open`], release with
 * [`tc_document_free`].
 */
typedef struct TcDocument TcDocument;

/**
 * An event delivered from the core to the shell.
 *
 * The struct and every string it points to are only valid for the
 * duration of the callback invocation; copy anything you need out of it.
 * Strings not applicable to the event kind are null.
 */
typedef struct TcEvent {
  /**
   * One of the `TC_EVENT_*` constants.
   */
  uint32_t kind;
  /**
   * Sequence number (pong events).
   */
  uint64_t seq;
  /**
   * File path (diagnostics) or project root (server status).
   */
  const char *path;
  /**
   * Server id (server status).
   */
  const char *server;
  /**
   * Status string (server status).
   */
  const char *status;
  /**
   * JSON payload (diagnostics) or message text (server status).
   */
  const char *payload;
} TcEvent;

/**
 * Shell-provided event sink. Invoked on the core's single dispatch thread;
 * implementations must hop to their UI thread themselves.
 */
typedef void (*TcEventCallback)(const struct TcEvent *event, void *userdata);

/**
 * An edit the core performed on itself via undo/redo, for the shell to
 * replay on its display cache: replace UTF-16 code units `start..end` with
 * `text`. `text` must be released with [`tc_string_free`].
 */
typedef struct TcAppliedEdit {
  uintptr_t start;
  uintptr_t end;
  char *text;
} TcAppliedEdit;

/**
 * One style of the theme. Colors are 0xRRGGBBAA for the light and dark
 * appearances; `flags` uses [`TC_STYLE_BOLD`]/[`TC_STYLE_ITALIC`].
 */
typedef struct TcStyle {
  uint32_t light;
  uint32_t dark;
  uint32_t flags;
} TcStyle;

/**
 * One styled span, in UTF-16 code units. `style` indexes the table from
 * [`tc_style_table`].
 */
typedef struct TcHighlightSpan {
  uintptr_t start;
  uintptr_t end;
  uint32_t style;
} TcHighlightSpan;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the core version as a static nul-terminated UTF-8 string.
 * The returned pointer is owned by the core; do not free it.
 */
const char *tc_version(void);

/**
 * Creates a core instance whose events are delivered to `callback`.
 *
 * `userdata` is passed back verbatim on every invocation and must remain
 * valid until after [`tc_app_free`] returns. Returns null if `callback` is
 * null.
 */
struct TcApp *tc_app_new(TcEventCallback callback, void *userdata);

/**
 * Requests an asynchronous pong event echoing `seq`.
 *
 * # Safety
 * `app` must be a live pointer from [`tc_app_new`].
 */
void tc_app_ping(struct TcApp *app, uint64_t seq);

/**
 * Destroys an app handle. Blocks until queued events have been delivered
 * and guarantees the callback is never invoked afterwards.
 *
 * # Safety
 * `app` must be a pointer from [`tc_app_new`], not previously freed.
 */
void tc_app_free(struct TcApp *app);

/**
 * Announces an opened document to the language-server pool: `path`, its
 * syntax `language` name, and the full `text`. Spawns the (server,
 * project-root) instance on first use; does nothing for languages
 * without a registered server.
 *
 * # Safety
 * `app` must be a live pointer from [`tc_app_new`]; each pointer/length
 * pair must describe readable UTF-8.
 */
void tc_lsp_did_open(struct TcApp *app,
                     const char *path,
                     uintptr_t path_len,
                     const char *language,
                     uintptr_t language_len,
                     const char *text,
                     uintptr_t text_len);

/**
 * Announces new contents for an opened document (full-text sync).
 *
 * # Safety
 * Same contract as [`tc_lsp_did_open`].
 */
void tc_lsp_did_change(struct TcApp *app,
                       const char *path,
                       uintptr_t path_len,
                       const char *text,
                       uintptr_t text_len);

/**
 * Requests hover information at an LSP position (zero-based line, UTF-16
 * column). Returns the request id whose `TC_EVENT_LSP_RESPONSE` event
 * will carry the answer, or 0 when the document has no server.
 *
 * # Safety
 * Same contract as [`tc_lsp_did_open`].
 */
uint64_t tc_lsp_hover(struct TcApp *app,
                      const char *path,
                      uintptr_t path_len,
                      uint32_t line,
                      uint32_t character);

/**
 * Requests the definition location(s) of the symbol at an LSP position;
 * same contract as [`tc_lsp_hover`]. The response's `result` is an LSP
 * `Location`, `Location[]`, or `LocationLink[]`.
 *
 * # Safety
 * Same contract as [`tc_lsp_did_open`].
 */
uint64_t tc_lsp_definition(struct TcApp *app,
                           const char *path,
                           uintptr_t path_len,
                           uint32_t line,
                           uint32_t character);

/**
 * Announces a closed document. The server instance stays warm.
 *
 * # Safety
 * Same contract as [`tc_lsp_did_open`].
 */
void tc_lsp_did_close(struct TcApp *app, const char *path, uintptr_t path_len);

/**
 * Creates an empty buffer.
 */
struct TcBuffer *tc_buffer_new(void);

/**
 * Destroys a buffer.
 *
 * # Safety
 * `buffer` must be a pointer from [`tc_buffer_new`], not previously freed.
 */
void tc_buffer_free(struct TcBuffer *buffer);

/**
 * Buffer length in bytes.
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`].
 */
uintptr_t tc_buffer_len_bytes(const struct TcBuffer *buffer);

/**
 * Buffer length in UTF-16 code units (the unit AppKit and LSP count in).
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`].
 */
uintptr_t tc_buffer_len_utf16(const struct TcBuffer *buffer);

/**
 * Inserts `len` bytes of UTF-8 at byte offset `offset`.
 *
 * Returns false — changing nothing — if the offset is out of bounds or not
 * a character boundary, or if the bytes are not valid UTF-8.
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`]; `text` must point
 * to `len` readable bytes.
 */
bool tc_buffer_insert(struct TcBuffer *buffer, uintptr_t offset, const char *text, uintptr_t len);

/**
 * Deletes the byte range `start..end`. Returns false, changing nothing, on
 * invalid ranges.
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`].
 */
bool tc_buffer_delete(struct TcBuffer *buffer, uintptr_t start, uintptr_t end);

/**
 * Replaces the UTF-16 code unit range `start..end` with `len` bytes of
 * UTF-8. This maps one-to-one onto an AppKit `NSRange` edit. Returns false,
 * changing nothing, on invalid input.
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`]; `text` must point
 * to `len` readable bytes.
 */
bool tc_buffer_replace_utf16(struct TcBuffer *buffer,
                             uintptr_t start,
                             uintptr_t end,
                             const char *text,
                             uintptr_t len);

/**
 * Returns the entire buffer contents as a nul-terminated UTF-8 string.
 * Release with [`tc_string_free`]. Returns null on allocation failure.
 *
 * # Safety
 * `buffer` must be a live pointer from [`tc_buffer_new`].
 */
char *tc_buffer_text(const struct TcBuffer *buffer);

/**
 * Releases a string returned by the core.
 *
 * # Safety
 * `s` must be a pointer returned by a `tc_*` function documented to be
 * released with this call, not previously freed.
 */
void tc_string_free(char *s);

/**
 * Creates an empty, pathless document.
 */
struct TcDocument *tc_document_new(void);

/**
 * Opens the file at `path` (`len` bytes of UTF-8). Returns null on failure
 * and, if `error_out` is non-null, stores a human-readable message there to
 * be released with [`tc_string_free`].
 *
 * # Safety
 * `path` must point to `len` readable bytes; `error_out`, if non-null, must
 * point to a writable pointer slot.
 */
struct TcDocument *tc_document_open(const char *path, uintptr_t len, char **error_out);

/**
 * Destroys a document.
 *
 * # Safety
 * `document` must be a pointer from a `tc_document_*` constructor, not
 * previously freed.
 */
void tc_document_free(struct TcDocument *document);

/**
 * Replaces the UTF-16 code unit range `start..end` with `len` bytes of
 * UTF-8, recording the edit in the undo history. Returns false, changing
 * nothing, on invalid input.
 *
 * # Safety
 * `document` must be a live document pointer; `text` must point to `len`
 * readable bytes.
 */
bool tc_document_replace_utf16(struct TcDocument *document,
                               uintptr_t start,
                               uintptr_t end,
                               const char *text,
                               uintptr_t len);

/**
 * Full document contents as a nul-terminated UTF-8 string; release with
 * [`tc_string_free`].
 *
 * # Safety
 * `document` must be a live document pointer.
 */
char *tc_document_text(const struct TcDocument *document);

/**
 * Document length in bytes.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
uintptr_t tc_document_len_bytes(const struct TcDocument *document);

/**
 * Document length in UTF-16 code units.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
uintptr_t tc_document_len_utf16(const struct TcDocument *document);

/**
 * Whether the document differs from its last saved state.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
bool tc_document_is_dirty(const struct TcDocument *document);

/**
 * Whether an undo step is available.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
bool tc_document_can_undo(const struct TcDocument *document);

/**
 * Whether a redo step is available.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
bool tc_document_can_redo(const struct TcDocument *document);

/**
 * Ends the current undo coalescing run (call when the caret moves or focus
 * changes, so the next keystroke starts a fresh undo step).
 *
 * # Safety
 * `document` must be a live document pointer.
 */
void tc_document_break_undo_group(struct TcDocument *document);

/**
 * Starts an explicit edit group: every edit until
 * [`tc_document_end_edit_group`] undoes as a single step (e.g. a
 * replace-all).
 *
 * # Safety
 * `document` must be a live document pointer.
 */
void tc_document_begin_edit_group(struct TcDocument *document);

/**
 * Commits the open edit group.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
void tc_document_end_edit_group(struct TcDocument *document);

/**
 * Undoes the newest step. On success returns true and stores an array of
 * edits — to be replayed on the display cache **in array order** — in
 * `edits_out`/`count_out`; release the array with
 * [`tc_applied_edits_free`]. Returns false (leaving the outputs zeroed)
 * when there is nothing to undo.
 *
 * # Safety
 * `document` must be a live document pointer; `edits_out` and `count_out`
 * must point to writable slots.
 */
bool tc_document_undo(struct TcDocument *document,
                      struct TcAppliedEdit **edits_out,
                      uintptr_t *count_out);

/**
 * Redoes the most recently undone step; same contract as
 * [`tc_document_undo`].
 *
 * # Safety
 * `document` must be a live document pointer; `edits_out` and `count_out`
 * must point to writable slots.
 */
bool tc_document_redo(struct TcDocument *document,
                      struct TcAppliedEdit **edits_out,
                      uintptr_t *count_out);

/**
 * Releases an edit array returned by [`tc_document_undo`] or
 * [`tc_document_redo`], including the strings it owns.
 *
 * # Safety
 * `edits` and `count` must be exactly the pair produced by one undo/redo
 * call, not previously freed.
 */
void tc_applied_edits_free(struct TcAppliedEdit *edits, uintptr_t count);

/**
 * Re-reads the document from its file. On success fills `edit_out` with
 * the single replacement to replay on the display cache (an empty range
 * and empty text means the buffer already matched the disk; release its
 * `text` with [`tc_string_free`]). The reload is one undo step, and the
 * document counts as clean afterwards. Returns false on failure and fills
 * the optional `error_out`.
 *
 * # Safety
 * `document` must be a live document pointer; `edit_out` must point to a
 * writable [`TcAppliedEdit`]; `error_out`, if non-null, must point to a
 * writable pointer slot.
 */
bool tc_document_reload(struct TcDocument *document,
                        struct TcAppliedEdit *edit_out,
                        char **error_out);

/**
 * Saves to the document's current path. Returns false on failure and, if
 * `error_out` is non-null, stores a message there (release with
 * [`tc_string_free`]). An untitled document fails; use
 * [`tc_document_save_as`].
 *
 * # Safety
 * `document` must be a live document pointer; `error_out`, if non-null,
 * must point to a writable pointer slot.
 */
bool tc_document_save(struct TcDocument *document, char **error_out);

/**
 * Saves to `path` (`len` bytes of UTF-8) and adopts it as the document's
 * path. Same error contract as [`tc_document_save`].
 *
 * # Safety
 * `document` must be a live document pointer; `path` must point to `len`
 * readable bytes; `error_out`, if non-null, must point to a writable
 * pointer slot.
 */
bool tc_document_save_as(struct TcDocument *document,
                         const char *path,
                         uintptr_t len,
                         char **error_out);

/**
 * The document's file path as a nul-terminated UTF-8 string, or null for
 * untitled documents. Release with [`tc_string_free`].
 *
 * # Safety
 * `document` must be a live document pointer.
 */
char *tc_document_path(const struct TcDocument *document);

/**
 * The document's encoding as a static human-readable name (e.g. "UTF-8").
 * Owned by the core; do not free.
 *
 * # Safety
 * `document` must be a live document pointer.
 */
const char *tc_document_encoding_name(const struct TcDocument *document);

/**
 * Loads the configuration file at `path` (`len` bytes of UTF-8). Always
 * returns a usable handle (defaults apply for anything missing or
 * unusable); if the file existed but could not be used and `warning_out`
 * is non-null, a human-readable warning is stored there for the shell to
 * surface once (release with [`tc_string_free`]).
 *
 * # Safety
 * `path` must point to `len` readable bytes; `warning_out`, if non-null,
 * must point to a writable pointer slot.
 */
struct TcConfig *tc_config_load(const char *path, uintptr_t len, char **warning_out);

/**
 * Destroys a configuration handle. Does not save.
 *
 * # Safety
 * `config` must be a pointer from [`tc_config_load`], not previously
 * freed.
 */
void tc_config_free(struct TcConfig *config);

/**
 * The configured editor font family, or null when the platform default
 * should be used. Release with [`tc_string_free`].
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
char *tc_config_font_family(const struct TcConfig *config);

/**
 * The editor font size in points (already clamped to the valid range).
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
double tc_config_font_size(const struct TcConfig *config);

/**
 * The tab width in columns (already clamped to the valid range).
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
uint32_t tc_config_tab_width(const struct TcConfig *config);

/**
 * The configured appearance, as a `TC_APPEARANCE_*` value.
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
uint32_t tc_config_appearance(const struct TcConfig *config);

/**
 * Sets the appearance choice (`TC_APPEARANCE_*`; unknown values mean
 * system).
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
void tc_config_set_appearance(struct TcConfig *config, uint32_t appearance);

/**
 * The project root for a file or directory path (`len` bytes of UTF-8):
 * the nearest ancestor with a root marker (VCS directory or
 * build/manifest file). Returns null for loose files outside any
 * project; release non-null results with [`tc_string_free`].
 *
 * # Safety
 * `path` must point to `len` readable bytes.
 */
char *tc_project_root_for_path(const char *path, uintptr_t len);

/**
 * Sets the editor font family; `len == 0` clears it back to the platform
 * default.
 *
 * # Safety
 * `config` must be a live configuration pointer; `family` must point to
 * `len` readable bytes.
 */
void tc_config_set_font_family(struct TcConfig *config, const char *family, uintptr_t len);

/**
 * Sets the editor font size in points (clamped to the valid range).
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
void tc_config_set_font_size(struct TcConfig *config, double size);

/**
 * Sets the tab width in columns (clamped to the valid range).
 *
 * # Safety
 * `config` must be a live configuration pointer.
 */
void tc_config_set_tab_width(struct TcConfig *config, uint32_t width);

/**
 * Writes the configuration back to its file: pretty-printed JSON, written
 * atomically, preserving keys this version does not recognize. If the
 * on-disk file was unparseable at load time it is first copied to
 * `<name>.bak`. Returns false on failure and fills the optional
 * `error_out` (release with [`tc_string_free`]).
 *
 * # Safety
 * `config` must be a live configuration pointer; `error_out`, if
 * non-null, must point to a writable pointer slot.
 */
bool tc_config_save(struct TcConfig *config, char **error_out);

/**
 * The theme's style table, indexed by the `style` of a highlight span.
 * Owned by the core and valid for the process lifetime; do not free.
 *
 * # Safety
 * `count_out` must point to a writable slot.
 */
const struct TcStyle *tc_style_table(uintptr_t *count_out);

/**
 * Sets the document's syntax language by name (`len == 0` clears it back
 * to plain text). Returns false for unknown names or documents beyond the
 * syntax size cap.
 *
 * # Safety
 * `document` must be a live document pointer; `name` must point to `len`
 * readable bytes.
 */
bool tc_document_set_language(struct TcDocument *document, const char *name, uintptr_t len);

/**
 * The document's syntax language name, or null for plain text. Release
 * with [`tc_string_free`].
 *
 * # Safety
 * `document` must be a live document pointer.
 */
char *tc_document_language_name(const struct TcDocument *document);

/**
 * Styled spans over the UTF-16 code unit range `start..end`, in
 * application order — where spans overlap, the later one wins. On success
 * stores the array in `spans_out`/`count_out` (empty is a success:
 * null/0); release with [`tc_highlight_spans_free`]. Returns false on
 * invalid ranges.
 *
 * # Safety
 * `document` must be a live document pointer; `spans_out` and `count_out`
 * must point to writable slots.
 */
bool tc_document_highlights(const struct TcDocument *document,
                            uintptr_t start,
                            uintptr_t end,
                            struct TcHighlightSpan **spans_out,
                            uintptr_t *count_out);

/**
 * Releases a span array from [`tc_document_highlights`].
 *
 * # Safety
 * `spans` and `count` must be exactly the pair produced by one highlights
 * call, not previously freed.
 */
void tc_highlight_spans_free(struct TcHighlightSpan *spans, uintptr_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
